version: '3.9'

networks:
  app-network:
    driver: bridge

volumes:
  cache:
    driver: local
  postgres_data:

services:
#  app:
#    restart: "no"
#    image: app
#    container_name: app
#    ports:
#      - '8000:8000'
#    depends_on:
#      - broker
#    networks:
#      - app-network

  db:
    image: 'postgres:13'
    restart: always
    container_name: db
    env_file:
      - ../.env
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=messenger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    networks:
      - app-network
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $${REDIS_PASSWORD}
    volumes:
      - cache:/data

  broker:
    image: apache/kafka:4.0.0
    container_name: broker
    ports:
      - '9092:9092'