CREATE TABLE chat_participants
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id   BIGINT                                  NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    joined_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    left_at   TIMESTAMP WITHOUT TIME ZONE,
    is_admin  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_chat_participants PRIMARY KEY (id)
);

CREATE TABLE chats
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    is_private BOOLEAN                                 NOT NULL,
    creator_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chats PRIMARY KEY (id)
);

CREATE TABLE communities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    description VARCHAR(500),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_communities PRIMARY KEY (id)
);

CREATE TABLE friend_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    sender_id    BIGINT                                  NOT NULL,
    recipient_id BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_friend_requests PRIMARY KEY (id)
);

CREATE TABLE friendships
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    friend_id  BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_friendships PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id    BIGINT                                  NOT NULL,
    sender_id  BIGINT                                  NOT NULL,
    content    TEXT                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    read_at    TIMESTAMP WITHOUT TIME ZONE,
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE post_community
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    community_id BIGINT                                  NOT NULL,
    post_id      BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_post_community PRIMARY KEY (id)
);

CREATE TABLE posts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creator_id BIGINT                                  NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    content    TEXT                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    read_at    TIMESTAMP WITHOUT TIME ZONE,
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE subscribes
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    community_id BIGINT                                  NOT NULL,
    member_id    BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_subscribes PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(15)                             NOT NULL,
    firstname   VARCHAR(25)                             NOT NULL,
    lastname    VARCHAR(25)                             NOT NULL,
    age         INTEGER                                 NOT NULL,
    gender      VARCHAR(255)                            NOT NULL,
    email       VARCHAR(35)                             NOT NULL,
    phonenumber VARCHAR(18)                             NOT NULL,
    password    TEXT,
    role        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE chats
    ADD CONSTRAINT FK_CHATS_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

ALTER TABLE chat_participants
    ADD CONSTRAINT FK_CHAT_PARTICIPANTS_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chats (id);

ALTER TABLE chat_participants
    ADD CONSTRAINT FK_CHAT_PARTICIPANTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE friendships
    ADD CONSTRAINT FK_FRIENDSHIPS_ON_FRIEND FOREIGN KEY (friend_id) REFERENCES users (id);

ALTER TABLE friendships
    ADD CONSTRAINT FK_FRIENDSHIPS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE friend_requests
    ADD CONSTRAINT FK_FRIEND_REQUESTS_ON_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES users (id);

ALTER TABLE friend_requests
    ADD CONSTRAINT FK_FRIEND_REQUESTS_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chats (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

ALTER TABLE post_community
    ADD CONSTRAINT FK_POST_COMMUNITY_ON_COMMUNITY FOREIGN KEY (community_id) REFERENCES communities (id);

ALTER TABLE post_community
    ADD CONSTRAINT FK_POST_COMMUNITY_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE subscribes
    ADD CONSTRAINT FK_SUBSCRIBES_ON_COMMUNITY FOREIGN KEY (community_id) REFERENCES communities (id);

ALTER TABLE subscribes
    ADD CONSTRAINT FK_SUBSCRIBES_ON_MEMBER FOREIGN KEY (member_id) REFERENCES users (id);