spring:
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        packagesToScan: ru.senla.javacourse.mutovin.messenger.db.entity
  docker:
    compose:
      enabled: false
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      write-dates-as-timestamps: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null
  flyway:
    enabled: true
    locations: classpath:ru.senla.javacourse.mutovin.messenger.db.migration
    baseline-on-migrate: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

token:
  signing:
    key: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true
      theme: monokai
    disable-swagger-default-url: true
  packages-to-scan: ru.senla.javacourse.mutovin.messenger
  paths-to-match: "/**"
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
