spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.packagesToScan=ru.senla.javacourse.mutovin.messenger.db.entity
spring.jpa.show-sql=true

spring.docker.compose.enabled=false
spring.config.import=optional:file:../.env

spring.cache.type=redis
spring.cache.cache-names= redis-cache
spring.data.redis.host= ${REDIS_HOST:localhost}
spring.data.redis.port= 6379
spring.data.redis.password= ${REDIS_PASSWORD:}

spring.datasource.url=jdbc:postgresql://db:9900/messenger
spring.datasource.username=postgres
spring.datasource.password=qwerty

#spring.jpa.hibernate.ddl-auto=none

token.signing.key=${JWT_SECRET:53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.syntaxHighlight.activated=true
springdoc.swagger-ui.syntaxHighlight.theme=monokai
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.packages-to-scan=ru.senla.javacourse.mutovin.messenger
springdoc.paths-to-match=/**
springdoc.show-actuator=true
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json
springdoc.writer-with-default-pretty-printer=true
springdoc.model-and-view-allowed=true

# Character Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# Jackson Configuration
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=false
spring.jackson.mapper.ACCEPT_CASE_INSENSITIVE_PROPERTIES=true
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true 